# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'In Progress'), ('R', 'Rejected'), ('S', 'Submitted')], default='S', max_length=10)),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Incubator')),
            ],
        ),
        migrations.CreateModel(
            name='IncubatorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Incubator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncubatorStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incubated_on', models.DateField(auto_now_add=True)),
                ('incubated_upto', models.DateField(blank=True)),
                ('is_incubated', models.BooleanField(default=True)),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Incubator')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='is_incubated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incubatorstartup',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Startup'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Startup'),
        ),
        migrations.AddField(
            model_name='incubator',
            name='incubated_startup',
            field=models.ManyToManyField(related_name='incubators', through='app.IncubatorStartup', to='app.Startup'),
        ),
        migrations.AddField(
            model_name='incubator',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_incubators', through='app.IncubatorRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
