# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180330_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatorpost',
            name='likes',
            field=models.ManyToManyField(related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
