# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incubatorpost',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Posts - Incubator'},
        ),
        migrations.AlterField(
            model_name='incubatorpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
