# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20180330_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='room',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='links',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='incubator',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='message',
            name='links',
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_recieved', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='request_msg',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_sent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ConnectionRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
